---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smx01-ipmi
  namespace: ipmi-updater
spec:
  dnsNames:
    - smx01-ipmi.eddey.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: smx01-ipmi-eddey-net-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smx02-ipmi
  namespace: ipmi-updater
spec:
  dnsNames:
    - smx02-ipmi.eddey.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: smx02-ipmi-eddey-net-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smx03-ipmi
  namespace: ipmi-updater
spec:
  dnsNames:
    - smx03-ipmi.eddey.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: smx03-ipmi-eddey-net-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smx04-ipmi
  namespace: ipmi-updater
spec:
  dnsNames:
    - smx04-ipmi.eddey.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: smx04-ipmi-eddey-net-tls
