apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ipmi-cert-pusher
  labels:
    app: ipmi-cert-pusher
spec:
  selector:
    matchLabels:
      app: ipmi-cert-pusher
  endpoints:
  - port: metrics
    interval: 60s
